name: jerupos
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  material_design_icons_flutter: 7.0.7296
  shared_preferences: ^2.0.8
  jwt_decoder: ^2.0.1
  flutter_native_splash: ^2.3.3
  provider: ^6.1.1
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.4
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  bot_toast: ^4.1.3
  web_socket_channel: ^2.4.0
  wakelock: ^0.6.2
  flutter_easyloading: ^3.0.5
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
